# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-19 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20181119_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='planner',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
